name: bilgec
description: "BilGeç Flashcard App MVP"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Varsayilan ikonlar
  cupertino_icons: ^1.0.8

  # Bizim eklediklerimiz
  provider: ^6.1.2
  flip_card: ^0.7.0
  flutter_spinkit: ^5.2.1
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/questions.json